In [95]:
import numpy as np
import cv2


# Q1: implement a linear regression model
data row1 > header 
 ### 1: data preprocessing 
       #i. apply to_add array to data where element 1 added to row 1 , element 2 added to row 2 and so on 
       #ii.apply to_Mult array to the data row by to 
 ### 2: get the prediction values using the hyposis function weight array (regression_model)

In [96]:
Data= np.array([[1000,1001,1002,1003],
                [8,18,28,38],
               [16,26,36,46],
               [4,14,24,44]],dtype="int64")

to_add=np.array([2,4,6])
to_mult=np.array([10,100,1000,1000])
regression_model=np.array([2,4,6,8])

In [97]:
##step1 print dataset without header row
Data = Data[1:,:]
print(Data)

[[ 8 18 28 38]
 [16 26 36 46]
 [ 4 14 24 44]]


In [98]:
###step2 i. to_Add
Data = Data + to_add.reshape(3,1)
print(Data)

[[10 20 30 40]
 [20 30 40 50]
 [10 20 30 50]]


In [99]:
##step3 ii. to_MUlt
Data = Data * to_mult
print(Data)

[[  100  2000 30000 40000]
 [  200  3000 40000 50000]
 [  100  2000 30000 50000]]


In [100]:
###step4 prediction results

Prediction = Data @ regression_model.reshape(4,1)
print(Prediction)

[[508200]
 [652400]
 [588200]]


# Q2. Transformation

### apply crop , rotation  to the image 

#1: convert image from  BGR scale to Gray , Red ,Green & Blue scale
#2: crop the right  half
#3: crop the right bottom quarter
#4: zoom in by remove the quarter border from all sides 
#5: flip on x-axis 
#6: flip on y-axis 

In [101]:
image=cv2.imread("image.jpg") ### in_BGR
cv2.imshow("original_image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [102]:
## step1 print image data 

print(image)

[[[246 236 236]
  [247 237 237]
  [248 238 238]
  ...
  [250 242 235]
  [250 242 235]
  [250 242 235]]

 [[246 236 236]
  [246 236 236]
  [247 237 237]
  ...
  [249 241 234]
  [249 241 234]
  [249 241 234]]

 [[245 235 235]
  [246 236 236]
  [247 237 237]
  ...
  [248 240 233]
  [248 240 233]
  [248 240 233]]

 ...

 [[ 28  35  20]
  [ 47  54  39]
  [ 65  72  59]
  ...
  [ 26  60  66]
  [ 26  60  66]
  [ 24  60  66]]

 [[ 39  46  31]
  [ 61  68  53]
  [ 75  82  69]
  ...
  [ 19  61  68]
  [ 19  60  69]
  [ 17  61  68]]

 [[ 75  85  69]
  [ 98 108  92]
  [107 116 103]
  ...
  [ 17  64  72]
  [ 17  63  74]
  [ 15  64  72]]]


In [103]:
## step2 print image shape

print(image.shape)

(183, 276, 3)


In [104]:
## step3  get the value of lx ,ly 

lx= len(image[:,0,0]) #image.shape[0]
ly= len(image[0,:,0]) #image.shape[1]

print(lx,ly)

183 276


In [105]:
### step4 image in gray scale 
cv2.imshow("Gray scale",image[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [106]:
### step 5 image in Blue scale
blue = np.concatenate((np.ones_like(image[:,:,0]).reshape(lx,ly,1),np.zeros_like(image[:,:,0]).reshape(lx,ly,1),np.zeros_like(image[:,:,0]).reshape(lx,ly,1)),axis=2)
print(blue.shape)
cv2.imshow("Blue Scale",image*blue)
cv2.waitKey(0)
cv2.destroyAllWindows()

(183, 276, 3)


In [107]:
### step 6 image in red scale 
red = np.concatenate((np.zeros_like(image[:,:,0]).reshape(lx,ly,1),np.zeros_like(image[:,:,0]).reshape(lx,ly,1),np.ones_like(image[:,:,0]).reshape(lx,ly,1)),axis=2)
print(red.shape)
cv2.imshow("Red Scale",image*red)
cv2.waitKey(0)
cv2.destroyAllWindows()

(183, 276, 3)


In [108]:
### step 7 image in Green scale 
green = np.concatenate((np.zeros_like(image[:,:,0]).reshape(lx,ly,1),np.ones_like(image[:,:,0]).reshape(lx,ly,1),np.zeros_like(image[:,:,0]).reshape(lx,ly,1)),axis=2)
print(green.shape)
cv2.imshow("Green scale",image*green)
cv2.waitKey(0)
cv2.destroyAllWindows()

(183, 276, 3)


In [109]:
# step 8 crop the right half
cv2.imshow("original_image",image)
cv2.imshow(" right half",image[:,ly//2:,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [110]:
## step 9 crop the right bottom quarter
cv2.imshow("gray",image[:,:,1])
cv2.imshow(" right bottom quarter",image[lx//2:,ly//2:,1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [111]:
## step 10 remove the quarter border from all sides 
cv2.imshow("original_image",image)
cv2.imshow(" zoom in ",image[lx//4:lx//4*3,ly//4:ly//4*3,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [112]:
## step 11 flip on x-axis 
cv2.imshow("original_image",image)
cv2.imshow(" flip the image in x axis ",image[::-1,:,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [113]:
## step 12 flip on y-axis
cv2.imshow("original_image",image)
cv2.imshow(" flip the image in y axis ",image[:,::-1,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

## Q3  Write a program to broadcast on different shapes of arrays where p(3,3) + q(3)

- p >> [[0, 0, 0],[1, 2, 3],[4, 5, 6]]
- q >> [10, 11, 12]

In [114]:
p = np.array([[0, 0, 0],[1, 2, 3],[4, 5, 6]])
q = np.array([10, 11, 12])
pq = p+q
print(pq)

[[10 11 12]
 [11 13 15]
 [14 16 18]]


## Q4 Write a NumPy program to make an array immutable 

In [115]:
a=np.ones(5)
a.flags.writeable = False
#a[1]=2

## Q5 Write a NumPy program to create a new array of 3*5, filled with 2

In [116]:
x = 2 * np.ones([3,5])
print(x)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


## Q6 Write a NumPy program to get the number of nonzero elements in an array

- array = [[0, 10, 20], [20, 0, 40]]

In [117]:
array = [[0, 10, 20], [20, 0, 40]]
print(np.count_nonzero(array))

4


## Q7 Write a NumPy program to get the minimum and maximum value of an array along the second axis

- create array 2x2 contains data from 0 to 3 

In [118]:
myrange = np.arange(0,4).reshape(2,2)
print(np.min(myrange,axis=1))
print(np.max(myrange,axis=1))

[0 2]
[1 3]


## Q8  Write a NumPy program to compute the mean, median,standard deviation, and variance of a given array 

- array = [0 4 2 1 3 5]

In [119]:
array = [0,4,2,1,3,5]
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))


2.5
2.5
1.707825127659933
2.9166666666666665
